version: 2

jobs:
  python3:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python -m venv ./venv
      - run: bash ./ci_scripts/circleci/install.sh
      - store_artifacts:
          path: doc/_build/
          destination: doc
      - store_artifacts:
          path: ~/log.txt
          destination: log.txt
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    docker:
      - image: circleci/python:3.6
    environment:
      # The github organization or username of the repository which hosts the
      # project and documentation.
      - USERNAME: ysig

      # The repository where the documentation will be hosted
      - DOC_REPO: GraKeL

      # The base URL for the Github page where the documentation will be hosted
      - DOC_URL: 0.1a10

      # The email is to be used for commits in the Github Page
      - EMAIL: y.siglidis@gmail.com

      # Deploy docs on pypi
      - DEPLOY_PYPI: false

      - PUSH_DOCS: false
 
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: bash ./ci_scripts/circleci/pypi_deploy.sh
      - run: bash ./ci_scripts/circleci/push_doc.sh

workflows:
  version: 2
  build-doc-and-deploy:
    jobs:
      - python3
      - deploy:
          requires:
            - python3
#          filters:
#            branches:
#              only: develop

